#!/bin/bash
#
# setup-egress-firewall.sh — Configure application-level egress firewall on Mac Mini
#
# LuLu (preferred): prints recommended rules to configure via GUI.
# pf (fallback):    writes anchor rules and prints activation instructions.
#
# Usage:
#   ./scripts/setup-egress-firewall.sh           # auto-detects LuLu vs pf
#   sudo ./scripts/setup-egress-firewall.sh      # required for pf fallback

set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Colour

info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; }

echo ""
echo "=== Hestia Egress Firewall Setup ==="
echo ""

# ── Allowed external endpoints ─────────────────────────────────────────────────
EXTERNAL_HOSTS=(
    "api.coinbase.com"
    "api.alpaca.markets"
    "api.anthropic.com"
    "api.openai.com"
    "generativelanguage.googleapis.com"
    "api.push.apple.com"
    "api.sandbox.push.apple.com"
    "pypi.org"
    "files.pythonhosted.org"
    "github.com"
    "ntfy.sh"
    "hc-ping.com"
)

LOCAL_ENDPOINTS=(
    "localhost:8443  (Hestia backend)"
    "localhost:11434 (Ollama)"
)

# ── LuLu path ─────────────────────────────────────────────────────────────────
LULU_APP="/Applications/LuLu.app"

if [[ -d "$LULU_APP" ]]; then
    # ── LuLu found: print recommended rules ───────────────────────────────────
    info "LuLu detected at $LULU_APP"
    echo ""
    echo "LuLu uses a GUI — configure the following ALLOW rules manually:"
    echo ""
    echo "  Open LuLu → Rules → Add Rule"
    echo ""
    echo "  Scope: Process = python3 (or the hestia venv python binary)"
    echo "         Direction: OUTGOING"
    echo ""

    echo "  ┌─────────────────────────────────────────────────────────┐"
    echo "  │ ALLOW — External hosts                                  │"
    echo "  ├─────────────────────────────────────────────────────────┤"
    for host in "${EXTERNAL_HOSTS[@]}"; do
        printf "  │  %-55s│\n" "$host"
    done
    echo "  └─────────────────────────────────────────────────────────┘"
    echo ""
    echo "  ┌─────────────────────────────────────────────────────────┐"
    echo "  │ ALLOW — Local endpoints (loopback, already safe)        │"
    echo "  ├─────────────────────────────────────────────────────────┤"
    for ep in "${LOCAL_ENDPOINTS[@]}"; do
        printf "  │  %-55s│\n" "$ep"
    done
    echo "  └─────────────────────────────────────────────────────────┘"
    echo ""
    echo "  Recommended default policy: BLOCK all outgoing, allow listed above."
    echo ""
    info "LuLu configuration complete (manual steps above). No system changes made."
    exit 0
fi

# ── LuLu NOT found: offer pf fallback ─────────────────────────────────────────
warn "LuLu not found at $LULU_APP"
echo ""
warn "LuLu (https://objective-see.org/products/lulu.html) is the preferred"
warn "egress firewall for macOS — it operates per-process (not system-wide)."
echo ""
echo "Falling back to pf (BSD Packet Filter) rules."
echo ""
warn "NOTE: pf rules are SYSTEM-WIDE (affect all processes, all users)."
warn "      LuLu is strongly preferred for application-level control."
echo ""

# Root check — pf requires root
if [[ "$EUID" -ne 0 ]]; then
    error "pf setup requires root. Re-run with: sudo $0"
    exit 1
fi

ANCHOR_FILE="/etc/pf.anchors/com.hestia.egress"
ANCHOR_NAME="com.hestia.egress"

info "Writing pf anchor to $ANCHOR_FILE ..."

cat > "$ANCHOR_FILE" <<'PF_RULES'
# com.hestia.egress — Hestia application egress whitelist
# Generated by scripts/setup-egress-firewall.sh
#
# Strategy: block all outgoing by default, pass only approved destinations.
# These rules operate at the network layer (not per-process like LuLu).
# LuLu (https://objective-see.org/products/lulu.html) is the preferred tool.

# --- Loopback (always allow) ---
pass out on lo0 all

# --- External API hosts (port 443/TCP only) ---
# Hestia trading APIs
pass out proto tcp to <hestia_egress_hosts> port 443 keep state

PF_RULES

# Append the pfctl table definition for allowed hosts
{
    echo ""
    echo "# Table populated by setup-egress-firewall.sh"
    echo "table <hestia_egress_hosts> persist { \\"
    last_idx=$(( ${#EXTERNAL_HOSTS[@]} - 1 ))
    for i in "${!EXTERNAL_HOSTS[@]}"; do
        host="${EXTERNAL_HOSTS[$i]}"
        if [[ $i -lt $last_idx ]]; then
            echo "    $host, \\"
        else
            echo "    $host }"
        fi
    done
} >> "$ANCHOR_FILE"

info "Anchor written to $ANCHOR_FILE"
echo ""

# ── Activation instructions ────────────────────────────────────────────────────
echo "=== Activation Instructions ==="
echo ""
echo "1. Add the anchor to /etc/pf.conf (insert before the last 'pass' line):"
echo ""
echo "     anchor \"$ANCHOR_NAME\""
echo "     load anchor \"$ANCHOR_NAME\" from \"$ANCHOR_FILE\""
echo ""
echo "2. Reload pf rules:"
echo ""
echo "     sudo pfctl -f /etc/pf.conf"
echo ""
echo "3. Enable pf if not already running:"
echo ""
echo "     sudo pfctl -e"
echo ""
echo "4. Verify the anchor loaded:"
echo ""
echo "     sudo pfctl -a $ANCHOR_NAME -s rules"
echo ""
echo "5. To make pf persistent across reboots, add to /etc/pf.conf as above."
echo "   pf is loaded on boot via /System/Library/LaunchDaemons/com.apple.pfctl.plist."
echo ""
warn "Reminder: pf blocks by network address, not by process. Any process on"
warn "          this Mac can reach the whitelisted hosts. Install LuLu for"
warn "          true application-level egress control."
echo ""
info "Done. Review $ANCHOR_FILE before activating."
