"""Proposal delivery — GitHub issues, macOS notifications, briefing integration."""
from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

from hestia.logging import get_logger
from hestia.logging.structured_logger import LogComponent
from hestia.dev.models import DevSession, DevPriority

logger = get_logger()

PROJECT_ROOT = Path.home() / "hestia"


class ProposalDelivery:
    """Delivers dev session proposals through multiple channels."""

    def __init__(self, notification_manager: Optional[Any] = None) -> None:
        self._notifications = notification_manager

    async def deliver_proposal(self, session: DevSession) -> Dict[str, Any]:
        """Deliver a proposal to all appropriate channels based on priority.

        Returns dict with delivery results per channel.
        """
        results = {}

        # Always create GitHub issue
        gh_result = await self.create_github_issue(session)
        results["github"] = gh_result

        # Notification based on priority
        if session.priority.value <= DevPriority.HIGH.value:
            notif_result = await self.send_notification(session)
            results["notification"] = notif_result

        return results

    async def create_github_issue(self, session: DevSession) -> Dict[str, Any]:
        """Create a GitHub issue for a proposal."""
        plan = session.plan or {}
        steps = plan.get("steps", [])
        files = plan.get("files", [])
        risk = plan.get("risk", "unknown")
        est_minutes = plan.get("estimated_minutes", "?")

        body = f"""## Hestia Dev Proposal

**Session:** `{session.id}`
**Source:** {session.source.value}
**Priority:** {session.priority.name}
**Risk:** {risk}
**Estimated:** ~{est_minutes} min

### Plan
{chr(10).join(f"- {s}" for s in steps) if steps else "No steps specified."}

### Files Affected
{chr(10).join(f"- `{f}`" for f in files) if files else "No files specified."}

### Description
{session.description}

---
*Approve this proposal by commenting `/approve` or from the Hestia macOS app.*
*Generated by Hestia Agentic Development System.*
"""

        labels = ["hestia-proposal"]
        if session.priority == DevPriority.CRITICAL:
            labels.append("critical")

        try:
            cmd = [
                "gh", "issue", "create",
                "--title", f"[hestia-proposal] {session.title}",
                "--body", body,
                "--label", ",".join(labels),
            ]
            result = subprocess.run(
                cmd, cwd=str(PROJECT_ROOT),
                capture_output=True, text=True, timeout=15,
            )
            if result.returncode == 0:
                issue_url = result.stdout.strip()
                logger.info(
                    f"Created GitHub issue for {session.id}: {issue_url}",
                    component=LogComponent.DEV,
                )
                return {"success": True, "url": issue_url}
            else:
                logger.warning(
                    f"GitHub issue creation failed: {result.stderr[:200]}",
                    component=LogComponent.DEV,
                )
                return {"success": False, "error": result.stderr[:200]}
        except (FileNotFoundError, subprocess.TimeoutExpired) as e:
            return {"success": False, "error": f"gh CLI unavailable: {type(e).__name__}"}

    async def send_notification(self, session: DevSession) -> Dict[str, Any]:
        """Send macOS notification for a proposal."""
        if not self._notifications:
            return {"success": False, "error": "Notification manager not available"}

        priority_map = {
            DevPriority.CRITICAL: "critical",
            DevPriority.HIGH: "high",
            DevPriority.NORMAL: "medium",
            DevPriority.LOW: "low",
            DevPriority.BACKGROUND: "low",
        }

        try:
            result = await self._notifications.create_bump(
                title=f"Dev Proposal: {session.title}",
                body=f"Priority: {session.priority.name} | Source: {session.source.value}",
                priority=priority_map.get(session.priority, "medium"),
                context={"session_id": session.id, "type": "dev_proposal"},
                actions=["approve", "skip", "details"],
            )
            return {"success": True, "callback_id": result.get("callbackId")}
        except Exception as e:
            logger.warning(
                f"Notification delivery failed: {type(e).__name__}",
                component=LogComponent.DEV,
            )
            return {"success": False, "error": type(e).__name__}

    def format_for_briefing(self, sessions: List[DevSession]) -> str:
        """Format pending proposals as a briefing section."""
        if not sessions:
            return ""

        lines = ["## Development Proposals\n"]
        for s in sessions:
            plan = s.plan or {}
            risk = plan.get("risk", "?")
            est = plan.get("estimated_minutes", "?")
            lines.append(f"- **{s.title}** (risk: {risk}, ~{est}min)")
            lines.append(f"  Session: `{s.id}` | Source: {s.source.value}")
            if plan.get("steps"):
                for step in plan["steps"][:3]:
                    lines.append(f"  - {step}")
            lines.append("")

        lines.append("*Approve with `/dev approve <id>` or from macOS Command tab.*")
        return "\n".join(lines)

    async def send_completion_notification(self, session: DevSession) -> Dict[str, Any]:
        """Notify Andrew that a dev session completed."""
        if not self._notifications:
            return {"success": False, "error": "Notification manager not available"}

        try:
            result = await self._notifications.create_bump(
                title=f"Dev Complete: {session.title}",
                body=f"Session {session.id} finished successfully. Tokens: {session.total_tokens:,}",
                priority="medium",
                context={"session_id": session.id, "type": "dev_complete"},
            )
            return {"success": True, "callback_id": result.get("callbackId")}
        except Exception as e:
            return {"success": False, "error": type(e).__name__}

    async def send_cancellation_notification(self, session: DevSession) -> Dict[str, Any]:
        """Notify that a session was cancelled (compensating action)."""
        if not self._notifications:
            return {"success": False}

        try:
            await self._notifications.create_bump(
                title=f"Dev Cancelled: {session.title}",
                body=f"Session {session.id} was cancelled.",
                priority="low",
                context={"session_id": session.id, "type": "dev_cancelled"},
            )
            return {"success": True}
        except Exception:
            return {"success": False}
